version: '3.1'

volumes:
  price-engine-data:

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - price-engine-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"